sentry.dsn=${SENTRY_DSN:}
server.compression.enabled=true
server.use-forward-headers=true
server.compression.mime-types=application/json,application/css,application/javascript,application/xml,text/html,text/xml,text/plain
spring.thymeleaf.cache=true
spring.cache.ehcache.config=classpath:ehcache.xml
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
# Topic tagging AI agent
topic.tags.ai.agent.url=${TOPIC_TAGS_AI_AGENT_URL:https://kbm2sc4qjqcubxjmkawniaei.agents.do-ai.run/api/v1/chat/completions}
topic.tags.ai.agent.key=${TOPIC_TAGS_AI_AGENT_KEY:}
