#!/usr/bin/env python3
"""Rebuild the Canadian address ranges that decide who the Academy's host redirects.

    python3 scripts/ops/generate_ca_ranges.py            # write the resources
    python3 scripts/ops/generate_ca_ranges.py --check    # compare, change nothing

Writes ``src/main/resources/geo/ca-ipv4.txt`` and ``ca-ipv6.txt``, which
``CanadianAddresses`` loads at startup and ``AcademyHostRedirectConfig`` consults on every
request to hadith.academyofislam.com: a reader the list places in Canada stays, everyone
else gets a 301 to the canonical host.

The source is the five regional registries' own ``delegated-extended`` statistics files.
They are public, authoritative and need no account or licence key, which is the reason for
shipping a list at all rather than calling a geolocation service - a lookup on every
request would put a third party in the path of every page, and the visitor addresses it
would be asked about are not ours to hand out.

Adjacent and overlapping ranges are merged, which roughly halves the row count and keeps
the binary search in CanadianAddresses shallow.

Two limits worth knowing before trusting the output, both inherent to registry data:

  * It records who an allocation was *issued* to, not where traffic *comes from*. A VPN
    exit node in Montreal whose block is registered in Panama reads as Panama, and no
    amount of regenerating fixes that.
  * A Canadian reseller operating inside a block registered to a parent abroad reads as
    the parent's country.

The list is stale the moment it is written and that is tolerable, because of the direction
it fails in: an address it cannot place is treated as outside Canada, so a reassigned block
moves to the canonical host rather than staying behind on a host being retired. Regenerate
it when the redirect is still in place a year from now, or when a Canadian reader reports
being redirected from an address the registries agree is Canadian.
"""

import argparse
import csv
import io
import ipaddress
import os
import sys
import urllib.request
import zipfile
from pathlib import Path

REGISTRIES = {
    "apnic": "https://ftp.apnic.net/stats/apnic/delegated-apnic-extended-latest",
    "arin": "https://ftp.arin.net/pub/stats/arin/delegated-arin-extended-latest",
    "ripencc": "https://ftp.ripe.net/pub/stats/ripencc/delegated-ripencc-extended-latest",
    "lacnic": "https://ftp.lacnic.net/pub/stats/lacnic/delegated-lacnic-extended-latest",
    "afrinic": "https://ftp.afrinic.net/pub/stats/afrinic/delegated-afrinic-extended-latest",
}
COUNTRY = "CA"
OUT_DIR = Path("src/main/resources/geo")
HEADER = (
    "# Canadian {family} ranges, start-end as unsigned {radix}, merged and sorted.\n"
    "# Generated by scripts/ops/generate_ca_ranges.py. Do not edit by hand; regenerate.\n"
    "#\n"
    "# Sources: the RIR delegated-extended statistics files, and GeoLite2 where the\n"
    "# generator was given MaxMind credentials. The registries record who an allocation\n"
    "# was issued to; GeoLite2 measures where a network answers from, which is what\n"
    "# places a VPN exit in the country it actually serves.\n"
    "#\n"
    "# This product includes GeoLite2 data created by MaxMind, available from\n"
    "# https://www.maxmind.com\n"
)


def fetch(name: str, url: str) -> str:
    print(f"  {name:8} fetching...", end="", flush=True)
    with urllib.request.urlopen(url, timeout=120) as response:
        body = response.read().decode("utf-8", errors="ignore")
    print(f" {len(body.splitlines())} rows")
    return body


def ranges_for(bodies: list[str]) -> tuple[list, list]:
    v4, v6 = [], []
    for body in bodies:
        for line in body.splitlines():
            parts = line.split("|")
            # registry|cc|type|start|value|date|status|...
            if len(parts) < 7 or parts[1] != COUNTRY:
                continue
            try:
                if parts[2] == "ipv4":
                    start = int(ipaddress.IPv4Address(parts[3]))
                    v4.append((start, start + int(parts[4]) - 1))
                elif parts[2] == "ipv6":
                    # For IPv6 the fifth field is a prefix length, not a count.
                    net = ipaddress.IPv6Network(f"{parts[3]}/{parts[4]}", strict=False)
                    v6.append((int(net.network_address), int(net.broadcast_address)))
            except (ipaddress.AddressValueError, ValueError):
                continue
    return v4, v6


MAXMIND_URL = ("https://download.maxmind.com/geoip/databases/"
               "GeoLite2-Country-CSV/download?suffix=zip")


def maxmind_ranges(account_id: str, licence_key: str) -> tuple[list, list]:
    """Canadian ranges as MaxMind sees them, which is not what the registries record.

    The registries record who an allocation was *issued* to. MaxMind measures where a
    network actually answers from. The gap between those is the whole reason for reading
    both: a VPN exit in Montreal on a block registered in Panama is Panama to a registry
    and Canada here, and it is a reader in Canada either way.

    Blocks are matched on ``geoname_id``, the network's own location, never on
    ``registered_country_geoname_id`` - taking the latter would just reproduce the
    registry answer we already have.
    """
    import base64

    class DropAuthOnRedirect(urllib.request.HTTPRedirectHandler):
        """The download 302s to a pre-signed URL that rejects a second credential.

        urllib replays every header on a redirect, so the Authorization header follows the
        request to storage and comes back 400. The signature in the redirect target is the
        credential there; this one has already done its job.
        """

        def redirect_request(self, req, fp, code, msg, headers, newurl):
            new = super().redirect_request(req, fp, code, msg, headers, newurl)
            if new is not None:
                new.remove_header("Authorization")
            return new

    token = base64.b64encode(f"{account_id}:{licence_key}".encode()).decode()
    request = urllib.request.Request(MAXMIND_URL, headers={"Authorization": f"Basic {token}"})
    opener = urllib.request.build_opener(DropAuthOnRedirect)
    print("  maxmind  fetching...", end="", flush=True)
    with opener.open(request, timeout=300) as response:
        payload = response.read()
    print(f" {len(payload) // 1024} KiB")

    v4, v6 = [], []
    with zipfile.ZipFile(io.BytesIO(payload)) as archive:
        names = archive.namelist()

        def member(suffix: str) -> str:
            return next(n for n in names if n.endswith(suffix))

        with archive.open(member("GeoLite2-Country-Locations-en.csv")) as handle:
            rows = csv.DictReader(io.TextIOWrapper(handle, encoding="utf-8"))
            canada = {r["geoname_id"] for r in rows if r["country_iso_code"] == COUNTRY}

        for suffix, bucket in (("Blocks-IPv4.csv", v4), ("Blocks-IPv6.csv", v6)):
            with archive.open(member(suffix)) as handle:
                for row in csv.DictReader(io.TextIOWrapper(handle, encoding="utf-8")):
                    if row["geoname_id"] in canada:
                        net = ipaddress.ip_network(row["network"])
                        bucket.append((int(net.network_address), int(net.broadcast_address)))
    return v4, v6


def merge(ranges: list) -> list:
    """Collapse overlapping and adjacent ranges, so the lookup stays shallow."""
    merged = []
    for start, end in sorted(ranges):
        if merged and start <= merged[-1][1] + 1:
            merged[-1][1] = max(merged[-1][1], end)
        else:
            merged.append([start, end])
    return merged


def render(merged: list, family: str, hex_mode: bool) -> str:
    out = [HEADER.format(family=family, radix="hex" if hex_mode else "decimal")]
    for start, end in merged:
        out.append(f"{start:032x} {end:032x}\n" if hex_mode else f"{start} {end}\n")
    return "".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="compare against the committed files and change nothing")
    parser.add_argument("--registries-only", action="store_true",
                        help="skip MaxMind even when credentials are present")
    args = parser.parse_args()

    if not OUT_DIR.is_dir():
        print(f"{OUT_DIR} not found - run this from the repository root", file=sys.stderr)
        return 2

    bodies = [fetch(name, url) for name, url in REGISTRIES.items()]
    v4, v6 = ranges_for(bodies)
    registry_only = (merge(v4), merge(v6))

    account_id = os.environ.get("MAXMIND_ACCOUNT_ID", "").strip()
    licence_key = os.environ.get("MAXMIND_LICENSE_KEY", "").strip()
    if args.registries_only or not (account_id and licence_key):
        if not args.registries_only:
            print("\n  MAXMIND_ACCOUNT_ID / MAXMIND_LICENSE_KEY not set - registries only.")
            print("  A VPN exit will read as its registered country, not where it answers.")
    else:
        m4, m6 = maxmind_ranges(account_id, licence_key)
        v4 += m4
        v6 += m6

    v4m, v6m = merge(v4), merge(v6)
    print(f"\n  ipv4 {len(v4)} rows -> {len(v4m)} merged")
    print(f"  ipv6 {len(v6)} rows -> {len(v6m)} merged")
    gained = sum(e - s + 1 for s, e in v4m) - sum(e - s + 1 for s, e in registry_only[0])
    if gained:
        print(f"  ipv4 addresses the registries alone would have missed: {gained:,}")

    if not v4m or not v6m:
        print("\nRefusing to write an empty table: every reader would be redirected.",
              file=sys.stderr)
        return 1

    wanted = {
        OUT_DIR / "ca-ipv4.txt": render(v4m, "IPv4", hex_mode=False),
        OUT_DIR / "ca-ipv6.txt": render(v6m, "IPv6", hex_mode=True),
    }
    changed = False
    for path, body in wanted.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == body:
            print(f"  {path} unchanged")
            continue
        changed = True
        if args.check:
            print(f"  {path} WOULD CHANGE")
        else:
            path.write_text(body, encoding="utf-8")
            print(f"  {path} written")

    if args.check and changed:
        print("\nThe committed ranges are out of date.")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
