kind: Deployment
apiVersion: apps/v1
metadata:
  name: rewayaat
  labels:
    app: rewayaat
  namespace: rewayaat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rewayaat
  template:
    metadata:
      labels:
        app: rewayaat
    spec:
      containers:
        - name: rewayaat
          image: $IMAGE
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 8081
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 30
          env:
            - name: "SPRING_ACTIVE_PROFILE"
              value: "PROD"
            - name: "ELASTIC_HOST"
              value: "$ELASTIC_HOST"
          
apiVersion: v1
kind: Service
metadata:
  name: rewayaat
  namespace: rewayaat
  labels:
    app.kubernetes.io/component: rewayaat
spec:
  type: ClusterIP
  selector:
    app: rewayaat
  ports:
    - port: 8080
      targetPort: 8080
      name: web
    - port: 8081
      targetPort: 8081
      name: metrics
