apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app: rewayaat
  name: rewayaat
spec:
  podMetricsEndpoints:
    - path: /actuator/metrics
      port: "metrics"
  selector:
    matchLabels:
      app.kubernetes.io/component: rewayaat
  namespaceSelector:
    matchNames:
      - rewayaat