apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rewayaat-v2
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://github.com/rewayaat/rewayaat.git
    targetRevision: master
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: rewayaat-v2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
