apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rewayaat-v2-management
  namespace: rewayaat-v2
spec:
  podSelector:
    matchLabels:
      app: rewayaat-v2
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8002
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: rewayaat-v2
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 8003
