apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rewayaat-v2
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - rewayaat-v2
  selector:
    matchLabels:
      app: rewayaat-v2
  endpoints:
    - port: management
      path: /actuator/prometheus
      interval: 30s
