name: Java CI

on: [ push ]

jobs:
  build:
    strategy:
      matrix:
        python:
          - 3.7.1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.1'
        - run: |
            pip install -U pip
            pip install awscli
      - name: "Run tests and build image"
        run: "mvn -q package docker:build"
      - name: "Deploy"
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          chmod a+x deploy.sh ecs_deploy.sh
          ./deploy.sh
      - uses: satackey/action-docker-layer-caching@v0.0.8
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Cache AWS dependencies
        uses: actions/cache@v2
        with:
          path: ~/.local/bin

env:
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}