name: Java CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      
      - name: "Run tests and build image"
        run: "mvn -q package docker:build"
      
      - name: "Push Image to DockerHub"
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          ./push-image.sh
    
      - name: Save DigitalOcean kubeconfig with short-lived credentials
        if: ${{ github.ref == 'refs/heads/master' }}
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.DO_KUBE_CLUSTER }}
      
      - name: Deploy to k8s
        if: ${{ github.ref == 'refs/heads/master' }}
        run: kubectl create ns rewayaat; sed -e 's|$CHANGE_CAUSE|test|g' manifests/deployment.yaml | sed -e 's|$BUILD_NUMBER|latest|g' | kubectl apply -f -
      
      - name: Verify deployment
        run: kubectl rollout status deployment/rewayaat -n rewayaat

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: satackey/action-docker-layer-caching@v0.0.8
        continue-on-error: true
      

env:
  DOCKER_EMAIL: ${{ secrets.DOCKER_EMAIL }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
  REMOTE_IMAGE_URL: ${{ secrets.REMOTE_IMAGE_URL }}
